program tests

  ! Driver program for FRUIT unit tests in:
  ! test/test_json.f90
  ! test/test_prior.f90
  ! test/test_model.f90
  ! test/test_linalg.f90
  ! test/test_util.f90
  ! test/test_gensys.f90
  ! test/test_random.f90
  ! test/test_smc.f90
  ! test/test_particles.f90

  ! Generated by FRUITPy.

  use mpi
  use fruit
  use test_json
  use test_prior
  use test_model
  use test_linalg
  use test_util
  use test_gensys
  use test_random
  use test_smc
  use test_particles
  !use test_model_circle_t, only: mm => model
  implicit none

  integer :: mpierr
  logical :: mpi_is_init, mpi_is_final

  !type(mm) :: m

  !m = mm()
  !print*,'Npara', m%npara
  !call m%getf

  call MPI_Initialized(mpi_is_init, mpierr)
  if (.not. mpi_is_init) call MPI_Init(mpierr)

  call init_fruit

  ! test/test_json.f90:
  call run_test_case(test_json1,"test_json1")
  ! 
  !! test/test_prior.f90:
  call run_test_case(test_prior_read_from_file,"test_prior_read_from_file")
  call run_test_case(test_prior_frank_er,"test_prior_frank_er")
  ! 
  !! test/test_model.f90:
  call run_test_case(test_model_initialize,"test_model_initialize")
  call run_test_case(test_model_likelihood,"test_model_likelihood")
  call run_test_case(test_model_prior,"test_model_prior")
  call run_test_case(test_model_policy,"test_model_policy")
  call run_test_case(test_model_policy_1,"test_model_policy_1")
  ! 
  !! test/test_linalg.f90:
  call run_test_case(test_dlyap,"test_dlyap")
  call run_test_case(test_determinant,"test_determinant")
  call run_test_case(test_cholesky,"test_cholesky")
  ! 
  !! test/test_util.f90:
  call run_test_case(test_read,"test_read")
  ! 
  !! test/test_gensys.f90:
  call run_test_case(test_gensys_sw,"test_gensys_sw")
  call run_test_case(test_gensys_ghls,"test_gensys_ghls")
  call run_test_case(test_gensys_indet,"no existence, uniqueness (?)")
  ! 
  !! test/test_random.f90:
  call run_test_case(test_random_init,"test_random_init")
  call run_test_case(test_mvn_norm,"test_mvn_norm")
  call run_test_case(test_passing_rng,"test_passing_rng")

  ! test/test_smc.f90:
  call run_test_case(test_smc_blocks,"test_smc_blocks")
  call run_test_case(test_smc_initialize,"test_smc_initialize")
  call run_test_case(test_smc_endog_ess,"test_smc_endog_ess")
  call run_test_case(test_smc_endog_schedule,"test_smc_endog_schedule")
  call run_test_case(test_smc_schedule,"test_smc_schedule")

  ! test/test_particles.f90:
  call run_test_case(test_basic,"test_basic")

  call fruit_summary
  call fruit_finalize

  call MPI_Finalized(mpi_is_final, mpierr)
  if (.not. mpi_is_final) call MPI_Finalize(mpierr)

end program tests
