package:
  name: fortress
  version: '0.1.5'

source:
  path: ..

build:
  binary_relocation: True
  detect_binary_files_with_prefix: True
    
requirements:
  build:
    - python=3.8
    - numpy 
    - {{ compiler('fortran') }}
    - mpich
    - flap
    - fruit 
    - fruitpy
    - fypp
    - json-fortran

  host:
    - python=3.8
    - numpy 
    - {{ compiler('fortran') }}
    - mpich
    - flap
    - fruit 
    - fruitpy
    - fypp
    - json-fortran

  run:
    - python
    - flap
    - fruit
    - fruitpy
    - openblas
    - mpich
    - tqdm
    - json-fortran 
    - numpy
    - tqdm
    - pandas
test:
  imports:
    - fortress

test:
  source_files:
    - test
    - makefile
    - src
