name: Wheels

on:
  push:
    tags: ["v*"]
  workflow_dispatch: {}

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13, macos-14, windows-2022]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: python -m pip install -U pip cibuildwheel

      - name: Install Intel oneAPI Fortran
        if: startsWith(matrix.os, 'windows')
        uses: rscohn2/setup-oneapi@v0
        with:
          components: ifx-compiler

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "cp310-* cp311-* cp312-*"
          CIBW_SKIP: "pp* *-musllinux_*"
          CIBW_ENVIRONMENT: >
            ENABLE_MPI=OFF
            USE_SYSTEM_JSONFORTRAN=OFF
            USE_SYSTEM_FLAP=OFF
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ENVIRONMENT_MACOS: >
            MACOSX_DEPLOYMENT_TARGET=11.0
            CMAKE_OSX_DEPLOYMENT_TARGET=11.0
          CIBW_ARCHS_WINDOWS: "AMD64"
          CMAKE_Fortran_COMPILER: ifx

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl
